### ISSUE TITLE
master branch currently broken with bitbang adapter?

### ISSUE THREAD

**Issue by floe** [mchck/programmer#9]
When I want to run current master branch with my nrf51 & BusPirate, I get the following error:

```
$ ruby -I. nrf51.rb name=buspirate:dev=/dev/ttyUSB0
/home/floe/src/programmer.git/adiv5-swd.rb:36:in `reset': undefined method `flush!' for #<BitbangSwd:0x000000023d2eb0> (NoMethodError)
	from /home/floe/src/programmer.git/adiv5-swd.rb:30:in `switch_to_swd'
	from /home/floe/src/programmer.git/adiv5-swd.rb:21:in `initialize'
	from /home/floe/src/programmer.git/backend-driver.rb:17:in `new'
	from /home/floe/src/programmer.git/backend-driver.rb:17:in `create'
	from /home/floe/src/programmer.git/backend-driver.rb:43:in `from_string_set'
	from /home/floe/src/programmer.git/backend-driver.rb:47:in `from_string'
	from nrf51.rb:170:in `<main>'
```

I can work around that by adding an empty `flush!` method in swd-bitbang.rb, but then I immediately run into the next error:

```
$ ruby -I. nrf51.rb name=buspirate:dev=/dev/ttyUSB0
nrf51.rb:8:in `detect': undefined method `IDR' for nil:NilClass (NoMethodError)
	from /home/floe/src/programmer.git/armv7.rb:22:in `initialize'
	from nrf51.rb:12:in `initialize'
	from nrf51.rb:171:in `new'
	from nrf51.rb:171:in `<main>'
```

And I'm not familiar enough with the code to tell why that happens...

**Comment by floe** [comment]
BTW, `git bisect` points to this commit as being responsible: https://github.com/mchck/programmer/commit/9cf676c25d3414d1a9a866e9045b3c90707474ab

**Comment by clouetb** [comment]
Hi,

got the same error here. For the records, I fixed it by defining a method calling the @lower class or whatever it is :
  def flush!
    @lower.flush!
  end

Hope this helps.
